# =============================================================================
# Odoo - Persistent Volume Claims
# =============================================================================

---
# PVC para datos de Odoo (filestore)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-pvc
  namespace: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: odoo
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
# PVC para addons personalizados
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons-pvc
  namespace: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: odoo
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
