# =============================================================================
# SYSTEM CRM (SGI) - Secrets
# =============================================================================
# ⚠️ NOTA: En producción usar Sealed Secrets o External Secrets
# Estos valores son placeholders - cambiar antes de desplegar
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: sgi-secrets
  namespace: sgi
  labels:
    app.kubernetes.io/name: sgi
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sgi:sgi-secret-2024@postgres.sgi.svc.cluster.local:5432/sgi"
  BETTER_AUTH_SECRET: "3oK3H2p66EKFQxlC6xkrhVoviBvaCdWDWHfj6BlQsGc="

---
# Secret para PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sgi
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  POSTGRES_USER: sgi
  POSTGRES_PASSWORD: sgi-secret-2024
  POSTGRES_DB: sgi

---
# Secret para pull de imágenes de ghcr.io (repo privado)
# Crear manualmente con:
# kubectl create secret docker-registry ghcr-secret \
#   --namespace sgi \
#   --docker-server=ghcr.io \
#   --docker-username=darwinva97 \
#   --docker-password=<GITHUB_PAT>
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: sgi
  labels:
    app.kubernetes.io/name: sgi
    app.kubernetes.io/component: registry
    app.kubernetes.io/managed-by: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  # Placeholder - reemplazar con credenciales reales o crear manualmente
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "REPLACE_WITH_BASE64_USER_PAT"
        }
      }
    }
