# =============================================================================
# SYSTEM CRM (SGI) - Secrets
# =============================================================================
# ⚠️ NOTA: En producción usar Sealed Secrets o External Secrets
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: sgi-secrets
  namespace: sgi
  labels:
    app.kubernetes.io/name: sgi
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sgi:sgi-secret-2024@postgres.sgi.svc.cluster.local:5432/sgi"
  BETTER_AUTH_SECRET: "3oK3H2p66EKFQxlC6xkrhVoviBvaCdWDWHfj6BlQsGc="

---
# Secret para PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sgi
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  POSTGRES_USER: sgi
  POSTGRES_PASSWORD: sgi-secret-2024
  POSTGRES_DB: sgi

# =============================================================================
# NOTA: El secret ghcr-secret debe crearse manualmente con:
#
# kubectl create secret docker-registry ghcr-secret \
#   --namespace sgi \
#   --docker-server=ghcr.io \
#   --docker-username=darwinva97 \
#   --docker-password=<GITHUB_PAT_CON_READ_PACKAGES>
#
# Luego hacer: kubectl label secret ghcr-secret -n sgi app.kubernetes.io/managed-by=manual
# =============================================================================
