# =============================================================================
# PERSISTENT VOLUME CLAIMS - Databases
# =============================================================================
# Storage persistente para PostgreSQL y MySQL
# =============================================================================

---
# PostgreSQL Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: databases
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
# MySQL Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: databases
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
