# =============================================================================
# ROOT APP OF APPS - CLUSTER K3S
# =============================================================================
# Este archivo define todas las aplicaciones que ArgoCD debe gestionar.
# Es el punto de entrada único para todo el cluster.
# =============================================================================

---
# =============================================================================
# INFRAESTRUCTURA - ArgoCD (autogestionado)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: infra/argocd
    
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace ya existe
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
        
  ignoreDifferences:
    # Ignorar campos de estado y metadata autogenerados
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
      name: argocd-initial-admin-secret
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    # Ignorar managedFields de todos los recursos
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - argocd-controller
        - argocd-application-controller
        - kube-controller-manager

---
# =============================================================================
# INFRAESTRUCTURA - Namespaces
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: infra/namespaces
    
  destination:
    server: https://kubernetes.default.svc
    # No namespace específico - los namespaces son cluster-scoped
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

---
# =============================================================================
# INFRAESTRUCTURA - Ingress Configuration
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-config
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: infra/ingress
    
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

---
# =============================================================================
# INFRAESTRUCTURA - Cert-Manager (Helm)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4
    helm:
      values: |
        installCRDs: true
        replicaCount: 1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# =============================================================================
# INFRAESTRUCTURA - Cert-Manager Issuers
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: infra/cert-manager
    
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

---
# =============================================================================
# INFRAESTRUCTURA - Databases (PostgreSQL + MySQL genéricos)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/databases

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

---
# =============================================================================
# APLICACIONES - Example App
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/example-app
    
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
        
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignorar si se usa HPA
---
# =============================================================================
# APLICACIONES - System CRM
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-crm
  namespace: argocd
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/system-crm
    
  destination:
    server: https://kubernetes.default.svc
    namespace: sgi
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
        
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

---
# =============================================================================
# APLICACIONES - OpenProject
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openproject
  namespace: argocd
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/openproject

  destination:
    server: https://kubernetes.default.svc
    namespace: openproject

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

---
# =============================================================================
# APLICACIONES - WAPI (WhatsApp API Gateway)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wapi
  namespace: argocd
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/wapi

  destination:
    server: https://kubernetes.default.svc
    namespace: wapi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

---
# =============================================================================
# APLICACIONES - Odoo (Marketing - Activa Capital)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: apps/odoo

  destination:
    server: https://kubernetes.default.svc
    namespace: odoo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

---
# =============================================================================
# INFRAESTRUCTURA - External-DNS (Cloudflare)
# =============================================================================
# Sincroniza automáticamente los Ingress con registros DNS de Cloudflare
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: git@github.com:darwinva97/kubernetes-cluster.git
    targetRevision: main
    path: infra/external-dns
    
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

---
# =============================================================================
# INFRAESTRUCTURA - Crossplane (Helm)
# =============================================================================
# Crossplane instalado para futuro uso con providers
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  labels:
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.14.5
    helm:
      values: |
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# =============================================================================
# NOTA: Los providers de Crossplane para Cloudflare están deshabilitados
# El provider oficial de Upbound para Cloudflare no está disponible actualmente.
# DNS se configura manualmente en Cloudflare hasta que haya un provider estable.
# =============================================================================

# ---
# # INFRAESTRUCTURA - Crossplane Providers (DESHABILITADO)
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: crossplane-providers
#   ...

# ---
# # INFRAESTRUCTURA - DNS Records (DESHABILITADO)
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
