# =============================================================================
# SEALED SECRET - Docker Registry htpasswd
# =============================================================================
# Este archivo contiene un SealedSecret que solo puede ser descifrado
# por el cluster donde esta instalado Sealed Secrets controller.
#
# PARA GENERAR UN NUEVO SEALED SECRET:
# =====================================
#
# 1. Generar el htpasswd (en tu maquina local):
#    htpasswd -Bbn admin tu-password-seguro > htpasswd
#
# 2. Crear el Secret temporal:
#    kubectl create secret generic registry-htpasswd \
#      --namespace=docker-registry \
#      --from-file=htpasswd \
#      --dry-run=client -o yaml > secret.yaml
#
# 3. Sellar el secret con kubeseal:
#    kubeseal --controller-name=sealed-secrets \
#      --controller-namespace=kube-system \
#      --format yaml < secret.yaml > sealed-secret.yaml
#
# 4. Copiar el contenido de sealed-secret.yaml aqui abajo
#
# 5. Eliminar archivos temporales:
#    rm htpasswd secret.yaml sealed-secret.yaml
#
# =============================================================================

---
# PLACEHOLDER: Reemplazar con el SealedSecret generado
# El SealedSecret tendra este formato:
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-htpasswd
  namespace: docker-registry
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: docker-registry
spec:
  encryptedData:
    # REEMPLAZAR: Pegar aqui el valor encriptado del htpasswd
    # Ejemplo: htpasswd: AgBy8i3...base64-encriptado...
    htpasswd: ""
  template:
    metadata:
      name: registry-htpasswd
      namespace: docker-registry
      labels:
        app.kubernetes.io/name: docker-registry
        app.kubernetes.io/component: registry
        app.kubernetes.io/part-of: docker-registry
    type: Opaque
